steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['deployment-manager', 'deployments', 'create', 'supernova-deployment', '--config', 'cloud_sql_v1.yaml']

- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: 'sh'
  args:
    - '-c'
    - sleep 300
options:
  logging: CLOUD_LOGGING_ONLY


